apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "mayo-demo"
  description: "Infra and applications for the Mayo A-Team."
  annotations:
    github.com/project-slug: fosterm-mw/mayo2
spec:
  type: project
  lifecycle: experimental
  owner: "user:guest"
